dist: xenial
sudo: required
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
cache:
  directories:
  - tmp/cache
services:
- docker
language: go
go:
- "1.11"
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - sourceline: deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu xenial
          main
      key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF6BC817356A3D45E
    packages:
    - docker-ce
    - socat
    - ebtables
before_install:
- sudo docker run -d -it --name nsenter ubuntu:16.04 bash && sudo docker cp nsenter:/usr/bin/nsenter /usr/local/bin/nsenter && sudo docker rm -f nsenter
- curl -Lo ./scripts/install-minikube.sh https://raw.githubusercontent.com/openpitrix/openpitrix/v0.4.1/deploy/kubernetes/scripts/install-minikube.sh
- bash ./scripts/install-minikube.sh
- curl -Lo ./scripts/init-helm.sh https://raw.githubusercontent.com/openpitrix/openpitrix/v0.4.1/deploy/kubernetes/scripts/init-helm.sh
- bash ./scripts/init-helm.sh
install:
- sudo apt-get install -y python-pip
- sudo pip install pybars3
- ./scripts/generate-values.sh -t
- ./scripts/deploy-openpitrix.sh
script:
- ./scripts/test-openpitrix.sh
before_deploy:
- ./scripts/generate-values.sh
- tar -zcvf openpitrix-helm-chart-$TRAVIS_TAG.tar.gz openpitrix
deploy:
  overwrite: true
  provider: releases
  api_key:
    secure: W1yZZUob56B8XS3GAzy40dh+NNx+TFpL8vXHwxbdCk9xjIX9PXlCkYnAofDzvQDQQbj8tF3URQcx8Uu0RlU6yOjrkiRZAjSdZXBmBvWi6zHXTqQlwouuFcsn73OgcoUpzYI8vNFv/cBqE7SsrX+Cu5zrIw+bRqGicg62fbkM4PUabZauWbyvvqBtl4p3ksdzMD5Gm3z9vps5HiC11wClkQzZO01cPrFDfqHCj8dg7PgOSEjUiGe1Nw++tfFBSz1eCAYqNylxRlqMCdNSFdYV4xETnLbHinnz74NuVX2ChDNW3+N5P4cN9q3c3fZ6FGoWo+rhyoFFyB4jRfDlL/fR0TfKoi/8Yod006jl6SB7VlswPX8gIcfPwyAt3niOp9bl/KQRNLGUOYP+sF/9n0+PxdiBqCfjHa45eEcUpSrKCNkLue3AorUOPKTqp+dsqYMheqON2KqSaLjGbbbbGG14lMARdUl5mnvaSqizWYa1jd2taApBjhkR4F/Tl6Uj5xTqFBegN9wJVsjQO9MrsL8c+g6QxC12dvRGSxZyM5q0Nx4UJ9oOv/sFhzFTNcHXNRChT6cy4SWFOtneJ0ZaXjaZqVZ+MAAsn79uWTFOZLfWrMyYbtar3ynt3L/T0hYCV3UzlaLyry4XFtCRsmCLcMk5nZNVE0W6Ooi+RteN4W4pUEY=
  file: openpitrix-helm-chart-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: openpitrix/helm-chart
    tags: true
