dist: xenial
sudo: required
services:
- docker
language: python
python: 2.7
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - sourceline: deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu xenial
        main
      key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF6BC817356A3D45E
    packages:
    - docker-ce
    - golang-go
    - socat
before_install:
- curl -Lo https://raw.githubusercontent.com/yudong2015/openpitrix/k8s_deploy_dev_20190412/deploy/kubernetes/scripts/install-minikube.sh
- sh install-minikube.sh
- curl -Lo https://raw.githubusercontent.com/yudong2015/openpitrix/k8s_deploy_dev_20190412/deploy/kubernetes/scripts/init-helm.sh
- sh init-helm.sh
install:
- sudo pip install pybars3
before_script:
- ./scripts/render-and-deploy-helm-chart.sh
script:
- travis_wait 20 ./scripts/test-openpitrix.sh
before_deploy:
- tar zcvf openpitrix-helm-chart-$TRAVIS_TAG.tar.gz openpitrix
deploy:
  overwrite: true
  provider: releases
  api_key:
    secure: k6pBb0kP99Sb0ZmJjncWZNugdUpT90dwWmvnlG4j8t+U61QarfgarR1RdDi8fYLKdioIOwfduH3SU5iq1Xtc4qV62f1J0mXvoRalcEhCeh16edaBxSIs1akUNirNjAvosKURcqmVpUXo+iRFhSI2708J2XBl8sogAqnuuW49LbcrsY7K4DrFFujjysBeSZDaRxPU8nMFykHNSrbEQgw2u/YK6PI0jg73RDhAfnr6cPfZr0ZJDr0ykLrra6faZLANR9khXKaTCN5JT3enI6ufd4bAY0WvjM6XeNLU9vWGeB5QbJErvLlkANrrtkCA6mRDVh6kUxkEM0R1VirGR4XJMk+kVdCzgJV4bpmQSzFhHVbr0g2+4hqeAvNrbVjGq6z9orbv//Lkg7IXhu21u/wcgSAzBWHZdMpoaAVPvySJSVAIhdCgJD5Q3Ebh7L3olLnQ0MWWf95Mz21jTaH0F76pe3Kcu/p3ATSsomZQL9ez+W1A0P+3Bxcjk4fjqjQDkrwBqxo4wTb0Oix66eZFJtwPWKqu0erzuViprSDi6+vwPydjt9ADxMWescFc53sfFPkQWzVC6Pfbxdqt4jCcgRBPipzchsbxHYaofKzfMJrJYIx67iR5Ai9Z8Nwwki6rGXocuR06uhuIyyN4j0yR6Y9qiCslvLUbptsU69WDkMlsOwI=
  file: openpitrix-helm-chart-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: openpitrix/helm-chart
    tags: true
